### ISSUE TITLE
Planter section. Need to be able to filter by Device identifier

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#116] opened 2021-06-15 08:16 UTC
In order to see how many (and who) is using one device we need to have the device identifier in the planter search filter.

**Comment by nmcharlton** [comment] 2021-06-15 09:12
Duplicate of #36

**Comment by nmcharlton** [comment] 2021-07-10 12:16
The `device_identifier` is associated with the `planter_registration` record, not the `planter` directly.
Therefore we need a change to the API server to extend filtering beyond the LoopBack template.

**Closed** 2021-11-08 18:59 UTC
Labels: type: enhancement, tool: Growers, size: medium, dependency: api
