### ISSUE TITLE
Bug: Filtering by Org, Species, Tags broken on Captures tool when selecting +1 verify status

### ISSUE THREAD

**Issue by gwynndp** [Greenstand/treetracker-admin-client#300] opened 2022-01-16 23:25 UTC
The filters appear to work when only ONE of the Verify Status options is selected, but seems to break when either ALL or more than one status is selected.  The filters are working on the Verify tool, for reference.  You can see the different # of captures for the same filter in the screenshots below.

The state for the filter is updating correctly, so the issue may be with the request or with the api.  

Captures Tool with ALL captures & Organization "test1" selected:
<img width="993" alt="Capture Data - Treetracker Admin by Greenstand 2022-01-16 15-19-39" src="https://user-images.githubusercontent.com/1761374/149682469-aec3806f-ab93-4e83-acaf-8aa40dd2ae54.png">

Verify Tool with ALL captures & Organization "test1" selected:
<img width="851" alt="Verify Captures - Treetracker Admin by Greenstand 2022-01-16 15-21-13" src="https://user-images.githubusercontent.com/1761374/149682492-75c7544a-9521-4941-bc77-51c263016abb.png">
O

**Comment by nmcharlton** [comment] 2022-01-17 07:12
Duplicate of #288

**Closed** 2022-02-02 01:58 UTC
Labels: type: bug, duplicate, size: medium, tool: Captures
