### ISSUE TITLE
Note field not showing in Tree details

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#240] opened 2021-12-10 17:02 UTC
This capture def. has the notes field filled out. 

![Screenshot 2021-12-10 at 19 57 16](https://user-images.githubusercontent.com/3283800/145612296-d0d1bbf7-be9a-4271-8bd3-a9acc95c7e57.png)

**Comment by nmcharlton** [comment] 2021-12-12 17:16
@sebastiangaertner This is caused by #220, which @tranquanghuy0801 has worked on.
The PR is just awaiting my review and should be completed shortly.

Duplicate of #220

**Comment by nmcharlton** [comment] 2021-12-12 17:16
Duplicate of #220

**Comment by nmcharlton** [comment] 2021-12-24 18:16
The fix to this has been deployed to production in https://github.com/Greenstand/treetracker-admin-client/releases/tag/v1.31.3

**Closed by nmcharlton** 2021-12-24 18:16 UTC
Labels: duplicate, priority
