### ISSUE TITLE
Grower Filter organization id "not set" is not working

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#951] opened 2022-11-18 07:56 UTC
when filtering by not set it shows all growers.

**Comment by nmcharlton** [comment] 2022-11-22 18:21
Likely fixed in #955 (to be retested after merge).

**Comment by nmcharlton** [comment] 2022-11-22 19:12
Duplicate of #869

**Comment by nmcharlton** [comment] 2022-12-03 16:01
Closing as duplicate

**Closed by nmcharlton** 2022-12-03 16:01 UTC
Labels: duplicate, on hold
