### ISSUE TITLE
Trees list is not displaying anything

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#41] opened 2021-03-11 08:31 UTC
No trees in the list view.

**Comment by nmcharlton** [comment] 2021-03-12 19:13
Duplicate of https://github.com/Greenstand/treetracker-admin-api/issues/485

**Comment by nmcharlton** [comment] 2021-03-15 10:34
Fixed in [v1.5.1](https://github.com/Greenstand/treetracker-admin-client/releases/tag/v1.5.1)

**Closed by nmcharlton** 2021-03-15 10:34 UTC
