### ISSUE TITLE
Verification tool and filter tools: Tags need to be organization specific.

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#756] opened 2022-07-20 12:19 UTC
Currently organization A will see all tags used that are in the Database entered by unrelated organizations. This is not practical. The list that is generated should only be coming from within the organization.

**Comment by nmcharlton** [comment] 2022-07-20 18:55
Duplicate of #620

**Comment by nmcharlton** [comment] 2023-01-27 22:42
Closing as duplicate. #620 is now complete.

**Closed by nmcharlton** 2023-01-27 22:42 UTC
Labels: duplicate, tool: Verify
