### ISSUE TITLE
Improve quick links on verification tool

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-client#49] opened 2021-03-25 22:13 UTC
This issue from Seb was found in the web map repo. It belongs here

See below the two images. Second icon should open the users map to quickly see the overview. (such as https://treetracker.org/?userid=3336)
Changing the order of icons first the pin icon with link to individual_tree, then the user_info_icon and then the user_map_icon
![usermap_link](https://user-images.githubusercontent.com/3283800/103736377-2e7c0080-5001-11eb-8ea0-5c1943f9b843.png)
![userinfo_link](https://user-images.githubusercontent.com/3283800/103736382-3176f100-5001-11eb-9626-53717a880660.png)

**Comment by nmcharlton** [comment] 2021-03-26 21:13
@deepwinter How old is this issue?
The user icon is active and displays the Planter side panel.

We have an similar active issue (#12) suggesting an extra icon be added to show a map with all of the user's trees.

**Comment by deepwinter** [comment] 2021-03-26 21:45
From Jan 5 this year

**Comment by nmcharlton** [comment] 2021-03-26 22:25
@sebastiangaertner Can you confirm that you're happy that the Planter Info icon is working on https://test-admin.treetracker.org and that the other half of the issue is covered by issue #12?

if so, we'll close this one as a duplicate.

**Comment by nmcharlton** [comment] 2021-04-10 20:38
Duplicate of #12

**Closed** 2021-04-16 06:03 UTC
Labels: capture verification, duplicate, enhancement, small
