### ISSUE TITLE
Growers: hover popup doesn't go away when clicking on grower details

### ISSUE THREAD

**Issue by OGreeni** [Greenstand/treetracker-admin-client#695] opened 2022-06-15 23:45 UTC
Hey, so I recently encountered this bug:

![image](https://user-images.githubusercontent.com/87455082/173960408-4b0a05a6-db06-4971-911d-51a7350d4159.png)

The hover popup on the grower profile persists even when clicking on the user's profile, which I believe isn't the intended behavior. The popup is still clickable and goes away once clicked.

**Comment by nmcharlton** [comment] 2022-06-16 19:36
duplicate of #664

**Comment by OGreeni** [comment] 2022-06-17 02:11
Currently working on a fix

**Comment by OGreeni** [comment] 2022-06-18 19:39
Hey, submitted my PR

**Closed** 2022-06-19 13:08 UTC
Labels: type: bug, tool: Growers, size: small
