### ISSUE TITLE
Verification is not working in version 1.6.2

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#55] opened 2021-03-27 15:52 UTC
No verification seems to work. 
See video attached... https://youtu.be/0w98AnS_-j8

**Comment by nmcharlton** [comment] 2021-03-27 15:58
@sebastiangaertner I'll take a look

**Comment by nmcharlton** [comment] 2021-03-28 11:28
This may be an issue with the permissions on the production database.
Verification works fine in dev and test environments, but returns a 500 Internal Server Error in prod.

**Comment by nmcharlton** [comment] 2021-03-29 06:50
@sebastiangaertner Can you confirm whether this is now working, following db permissions changes?

**Comment by nmcharlton** [comment] 2021-04-07 18:59
This was caused by a combination of incorrect database permissions in production and having verify publishing enabled but not supported in that environment (addressed by [this commit in treetracker-admin-api](https://github.com/Greenstand/treetracker-admin-api/commit/35b6c0103cd9e5d7a4e5489f13c15e34f9de741f)).

**Closed by nmcharlton** 2021-04-07 18:59 UTC
Labels: bug
