### ISSUE TITLE
Verify toool: Can not reject a single capture 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#683] opened 2022-06-09 08:17 UTC
When rejecting a capture there is no indication on progress and nothing is reloading or showing success. Message  showing after many seconds with "Failed to approve a capture"

**Comment by nmcharlton** [comment] 2022-06-11 20:17
@sebastiangaertner I haven't been able to reproduce this issue so far. Next time you see it, can you check the Network tab in the browser developer console and report the error here?
I wonder whether it's a transient issue with the gateway that we've seen occasionally in the past (503 error).

**Comment by ZavenArra** [comment] 2022-06-14 16:50
Seb reports this only happens for the first one in a session.

**Comment by sebastiangaertner** [comment] 2022-06-14 16:51
<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><meta name="theme-color" content="#000000"/><link rel="manifest" href="/manifest.json"/><link rel="shortcut icon" href="/favicon.ico"/><link rel="apple-touch-icon" href="/logo_192x192.png"/><title>Treetracker Admin by Greenstand</title><script async src="https://www.googletagmanager.com/gtag/js?id=UA-1280531-65"></script><script>function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","UA-1280531-65")</script><link href="/static/css/2.1ca50200.chunk.css" rel="stylesheet"><link href="/static/css/main.f9b76387.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(e){function r(r){for(var n,a,i=r[0],c=r[1],l=r[2],s=0,p=[];s<i.length;s++)a=i[s],Object.prototype.hasOwnProperty.call(o,a)&&o[a]&&p.push(o[a][0]),o[a]=0;for(n in c)Object.prototype.hasOwnProperty.call(c,n)&&(e[n]=c[n]);for(f&&f(r);p.length;)p.shift()();return u.push.apply(u,l||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,i=1;i<t.length;i++){var c=t[i];0!==o[c]&&(n=!1)}n&&(u.splice(r--,1),e=a(a.s=t[0]))}return e}var n={},o={1:0},u=[];function a(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,a),t.l=!0,t.exports}a.e=function(e){var r=[],t=o[e];if(0!==t)if(t)r.push(t[2]);else{var n=new Promise((function(r,n){t=o[e]=[r,n]}));r.push(t[2]=n);var u,i=document.createElement("script");i.charset="utf-8",i.timeout=120,a.nc&&i.setAttribute("nonce",a.nc),i.src=function(e){return a.p+"static/js/"+({}[e]||e)+"."+{3:"b6c8ad42",4:"d9f0294e"}[e]+".chunk.js"}(e);var c=new Error;u=function(r){i.onerror=i.onload=null,clearTimeout(l);var t=o[e];if(0!==t){if(t){var n=r&&("load"===r.type?"missing":r.type),u=r&&r.target&&r.target.src;c.message="Loading chunk "+e+" failed.\n("+n+": "+u+")",c.name="ChunkLoadError",c.type=n,c.request=u,t[1](c)}o[e]=void 0}};var l=setTimeout((function(){u({type:"timeout",target:i})}),12e4);i.onerror=i.onload=u,document.head.appendChild(i)}return Promise.all(r)},a.m=e,a.c=n,a.d=function(e,r,t){a.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},a.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},a.t=function(e,r){if(1&r&&(e=a(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(a.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)a.d(t,n,function(r){return e[r]}.bind(null,n));return t},a.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(r,"a",r),r},a.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},a.p="/",a.oe=function(e){throw console.error(e),e};var i=this["webpackJsonptreetracker-admin-client"]=this["webpackJsonptreetracker-admin-client"]||[],c=i.push.bind(i);i.push=r,i=i.slice();for(var l=0;l<i.length;l++)r(i[l]);var f=c;t()}([])</script><script src="/static/js/2.28f56746.chunk.js"></script><script src="/static/js/main.896e826f.chunk.js"></script></body></html>

**Comment by sebastiangaertner** [comment] 2022-06-14 16:59
![Image](https://user-images.githubusercontent.com/3283800/173634402-3d79ff76-bbcf-444a-967b-31bb562d055e.png)
![Image](https://user-images.githubusercontent.com/3283800/173634403-c8c8faaf-5501-4693-956d-113743dc4a5d.png)

**Comment by ZavenArra** [comment] 2022-06-14 18:18
https://stackoverflow.com/questions/57477805/why-do-i-get-fetch-failed-loading-when-it-actually-worked ??

**Comment by ZavenArra** [comment] 2022-06-14 18:25
@sebastiangaertner We are thinking this is a bug in your web browser.   What version of Chrome(?) are you using?

**Comment by nmcharlton** [comment] 2022-06-15 20:27
An issue was identified with the mappings in the API gateway, which has now been resolved.
This appears to have resolved the problem, so I will close this issue. It can be reopened if the problem flares up again and turns out to be caused by the Admin Panel.

**Closed by nmcharlton** 2022-06-15 20:27 UTC
Labels: type: bug, priority

**Comment by sebastiangaertner** [comment] 2022-06-15 20:50
so far so good. it seems to work nicely now!
