### ISSUE TITLE
Show (freetown) statistic cards for all organizations that have child entities

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#311] opened 2022-01-22 09:28 UTC
We should really offer this to all orgs. We have currently only about 5 orgs that fall into this category. It would be great to get that live.

**Comment by nmcharlton** [comment] 2023-01-27 22:08
We need an update to the reporting API to allow us to filter by organization,

**Comment by nmcharlton** [comment] 2023-01-27 22:35
Duplicate of #654

**Closed by nmcharlton** 2023-01-27 22:35 UTC
Labels: tool: Dashboard, size: small, dependency: api
