### ISSUE TITLE
Payments Filter not working

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#608] opened 2022-03-30 03:43 UTC
Refer to https://github.com/Greenstand/treetracker-admin-api/issues/629

**Comment by nmcharlton** [comment] 2022-07-02 11:43
@dadiorchen @Tarek-Bohdima Can this be closed? It appears to be working in production.

**Comment by Tarek-Bohdima** [comment] 2022-07-02 17:21
@nmcharlton the payment filter problem in #629 was closed as duplicate and kept here, but it is not resolved yet as i tested it now.
Problem : in Payments : 
Steps to reproduce:
- Click on Filter
- Organization : choose any one
- Apply -> keep loading and nothing shows
- Click on Filter again
- Reset -> Nothing happens
- Refresh page is the only solution

**Comment by nmcharlton** [comment] 2022-07-02 19:36
Thanks @Tarek-Bohdima

It looks like pressing Apply or Reset in the filter adds unsupported parameters to the API query (`GET https://test-k8s.treetracker.org/earnings/earnings`), triggering a 422 error (Unprocessable Entity):
```
offset: 0
sort_by: calculated_at
order: desc
limit: 20
earnings_status: all
organization_id: 80                                     <-- Not allowed by API
grower:                                                 <-- Can't be empty, should be omitted
payment_status: all                                     <-- Not allowed by API
phone:                                                  <-- Can't be empty, should be omitted
sub_organization: df12ea71-65e6-4059-b4f5-60c675764497
```

We should also handle the error more gracefully so the user isn't left waiting for something to happen (see #718 for a similar bug in the Earnings tool).

**Comment by tranquanghuy0801** [comment] 2022-07-21 22:52
@nmcharlton if `organization_id` field is not allow by API, does that mean we should remove that field in Payment Filters?

**Comment by nmcharlton** [comment] 2022-07-25 06:47
> @nmcharlton if `organization_id` field is not allow by API, does that mean we should remove that field in Payment Filters?

Yes. The API instead uses `sub_organization` to filter by org.

**Comment by thawansilva** [comment] 2022-10-25 14:47
Hello, I am Thawan, I would like to work on this issue!

**Closed** 2022-11-14 20:10 UTC
Labels: type: bug, good first issue, size: small, tool: Earnings
